### ISSUE TITLE
Generic training issue: the lod1 stage's training code can't extract mesh reliable

### ISSUE THREAD

**Issue by jerryxu9905** [xxlong0/SparseNeuS#7]
Hi, thanks for your excellent paper and codes!
I have ran your training codes (only in generic stage not in finetune stage), **but find the **_lod1_** stage's results are confusing**.

**In _lod0_ stage, mesh extracted seem reliable**, I trained _190k_ iterations in **_lod0_** stage and save the checkpoint. Then I use this checkpoint as the resumed checkpoint at the beginning of **_lod1_** stage's training.(the codes released have some issue in loading **_lod0_** stage's checkpoint, I manually modify `load_checkpoint` function). The mesh extracted after about _190k_ iterations as shown below: 
![2](https://user-images.githubusercontent.com/97662087/185592419-0414e774-a249-4fc9-b744-a76b29022b36.jpg)

**In **_lod1_** stage , the mesh extracted seem unreliable**. The mesh extracted after about _60k_ iterations as shown below: 
![1](https://user-images.githubusercontent.com/97662087/185591836-530a7e45-2572-42d8-82a5-1a81c28dc0f0.jpg)

I don't modify any conf files or any network parameters, My colleague found the same confusing results as mine in **_lod1_** stage's training.

Is there any error in released codes?

**Comment by flamehaze1115** [comment]
Sorry for the inconvenience. I will check the code, and back asap.

Best
Xiaoxiao
________________________________
发件人: jerryxu9905 ***@***.***>
发送时间: Friday, August 19, 2022 5:58:15 PM
收件人: xxlong0/SparseNeuS ***@***.***>
抄送: Subscribed ***@***.***>
主题: [xxlong0/SparseNeuS] Generic training issue: the lod1 stage's training code can't extract mesh reliable (Issue #7)


Hi, thanks for your excellent paper and codes!
I have ran your training codes (only in generic stage not in finetune stage), but find the lod1 stage's results are confusing.

In lod0 stage, mesh extracted seem reliable, I trained 190k iterations in lod0 stage and save the checkpoint. Then I use this checkpoint as the resumed checkpoint at the beginning of lod1 stage's training.(the codes released have some issue in loading lod0 stage's checkpoint, I manually modify load_checkpoint function). The mesh extracted after about 190k iterations as shown below:
[2]<https://user-images.githubusercontent.com/97662087/185592419-0414e774-a249-4fc9-b744-a76b29022b36.jpg>

In lod1 stage , the mesh extracted seem unreliable. The mesh extracted after about 60k iterations as shown below:
[1]<https://user-images.githubusercontent.com/97662087/185591836-530a7e45-2572-42d8-82a5-1a81c28dc0f0.jpg>

I don't modify any conf files or any network parameters, My colleague found the same confusing results as mine in lod1 stage's training.

Is there any error in released codes?

―

**Comment by youmi-zym** [comment]
Hi @flamehaze1115 @jerryxu9905 ,

Same to you, I modified the code to train the model in lod1 mode:

> In lod0 stage, mesh extracted seems reliable, I trained 190k iterations in lod0 stage and save the checkpoint. Then I use this checkpoint as the resumed checkpoint at the beginning of lod1 stage's training. (the codes released have some issues in loading lod0 stage's checkpoint, I manually modify the load_checkpoint function).

The mesh extracted after 60k training is good for me. 

![6k00](https://user-images.githubusercontent.com/17737537/185600191-d170325b-4be3-4957-8e4b-e3912ce728ec.png)

![60k_curve](https://user-images.githubusercontent.com/17737537/185600502-3f44505c-d3cc-4ca2-b158-dd4f8ab894ac.png)

The modified load_checkpoint function likes this:

```python

    def load_checkpoint(self, checkpoint_name):

        def load_state_dict(network, checkpoint, comment):
            if network is not None:
                if comment not in checkpoint.keys():
                    print(f'{comment} does not exist in checkpoint!')
                    return
                try:
                    pretrained_dict = checkpoint[comment]

                    model_dict = network.state_dict()

                    # 1. filter out unnecessary keys
                    pretrained_dict = {k: v for k, v in pretrained_dict.items() if k in model_dict and model_dict[k].shape == pretrained_dict[k].shape}
                    # 2. overwrite entries in the existing state dict
                    model_dict.update(pretrained_dict)
                    # 3. load the new state dict
                    msg = network.load_state_dict(pretrained_dict, strict=False)
                    print(colored(comment + " load successes", 'yellow'))
                    print(msg)
                except:
                    print(colored(comment + " load fails", 'yellow'))

        checkpoint = torch.load(os.path.join(self.base_exp_dir, 'checkpoints', checkpoint_name),
                                map_location=self.device)

        load_state_dict(self.rendering_network_outside, checkpoint, 'rendering_network_outside')

        load_state_dict(self.sdf_network_lod0, checkpoint, 'sdf_network_lod0')
        load_state_dict(self.sdf_network_lod1, checkpoint, 'sdf_network_lod1')

        load_state_dict(self.pyramid_feature_network, checkpoint, 'pyramid_feature_network')
        load_state_dict(self.pyramid_feature_network_lod1, checkpoint, 'pyramid_feature_network_lod1')

        load_state_dict(self.variance_network_lod0, checkpoint, 'variance_network_lod0')
        load_state_dict(self.variance_network_lod1, checkpoint, 'variance_network_lod1')

        load_state_dict(self.rendering_network_lod0, checkpoint, 'rendering_network_lod0')
        load_state_dict(self.rendering_network_lod1, checkpoint, 'rendering_network_lod1')

        if self.restore_lod0:  # use the trained lod0 networks to initialize lod1 networks
            print('\nLoad lod1 from lod0!\n')
            load_state_dict(self.sdf_network_lod1, checkpoint, 'sdf_network_lod0')
            load_state_dict(self.pyramid_feature_network_lod1, checkpoint, 'pyramid_feature_network')
            load_state_dict(self.rendering_network_lod1, checkpoint, 'rendering_network_lod0')

        if self.is_continue and (not self.restore_lod0):
            try:
                self.optimizer.load_state_dict(checkpoint['optimizer'])
            except:
                print(colored("load optimizer fails", "yellow"))
            self.iter_step = checkpoint['iter_step']
            self.val_step = checkpoint['val_step'] if 'val_step' in checkpoint.keys() else 0

        self.logger.info('End')

```

**Comment by jerryxu9905** [comment]
Hi @youmi-zym ,
Thank you for your sharing!!!



> Hi @flamehaze1115 @jerryxu9905 ,
> 
> Same to you, I modified the code to train the model in lod1 mode:
> 
> > In lod0 stage, mesh extracted seems reliable, I trained 190k iterations in lod0 stage and save the checkpoint. Then I use this checkpoint as the resumed checkpoint at the beginning of lod1 stage's training. (the codes released have some issues in loading lod0 stage's checkpoint, I manually modify the load_checkpoint function).
> 
> The mesh extracted after 60k training is good for me.
> 
> ![6k00](https://user-images.githubusercontent.com/17737537/185600191-d170325b-4be3-4957-8e4b-e3912ce728ec.png)
> 
> ![60k_curve](https://user-images.githubusercontent.com/17737537/185600502-3f44505c-d3cc-4ca2-b158-dd4f8ab894ac.png)
> 
> The modified load_checkpoint function likes this:
> 
> ```python
>     def load_checkpoint(self, checkpoint_name):
> 
>         def load_state_dict(network, checkpoint, comment):
>             if network is not None:
>                 if comment not in checkpoint.keys():
>                     print(f'{comment} does not exist in checkpoint!')
>                     return
>                 try:
>                     pretrained_dict = checkpoint[comment]
> 
>                     model_dict = network.state_dict()
> 
>                     # 1. filter out unnecessary keys
>                     pretrained_dict = {k: v for k, v in pretrained_dict.items() if k in model_dict and model_dict[k].shape == pretrained_dict[k].shape}
>                     # 2. overwrite entries in the existing state dict
>                     model_dict.update(pretrained_dict)
>                     # 3. load the new state dict
>                     msg = network.load_state_dict(pretrained_dict, strict=False)
>                     print(colored(comment + " load successes", 'yellow'))
>                     print(msg)
>                 except:
>                     print(colored(comment + " load fails", 'yellow'))
> 
>         checkpoint = torch.load(os.path.join(self.base_exp_dir, 'checkpoints', checkpoint_name),
>                                 map_location=self.device)
> 
>         load_state_dict(self.rendering_network_outside, checkpoint, 'rendering_network_outside')
> 
>         load_state_dict(self.sdf_network_lod0, checkpoint, 'sdf_network_lod0')
>         load_state_dict(self.sdf_network_lod1, checkpoint, 'sdf_network_lod1')
> 
>         load_state_dict(self.pyramid_feature_network, checkpoint, 'pyramid_feature_network')
>         load_state_dict(self.pyramid_feature_network_lod1, checkpoint, 'pyramid_feature_network_lod1')
> 
>         load_state_dict(self.variance_network_lod0, checkpoint, 'variance_network_lod0')
>         load_state_dict(self.variance_network_lod1, checkpoint, 'variance_network_lod1')
> 
>         load_state_dict(self.rendering_network_lod0, checkpoint, 'rendering_network_lod0')
>         load_state_dict(self.rendering_network_lod1, checkpoint, 'rendering_network_lod1')
> 
>         if self.restore_lod0:  # use the trained lod0 networks to initialize lod1 networks
>             print('\nLoad lod1 from lod0!\n')
>             load_state_dict(self.sdf_network_lod1, checkpoint, 'sdf_network_lod0')
>             load_state_dict(self.pyramid_feature_network_lod1, checkpoint, 'pyramid_feature_network')
>             load_state_dict(self.rendering_network_lod1, checkpoint, 'rendering_network_lod0')
> 
>         if self.is_continue and (not self.restore_lod0):
>             try:
>                 self.optimizer.load_state_dict(checkpoint['optimizer'])
>             except:
>                 print(colored("load optimizer fails", "yellow"))
>             self.iter_step = checkpoint['iter_step']
>             self.val_step = checkpoint['val_step'] if 'val_step' in checkpoint.keys() else 0
> 
>         self.logger.info('End')
> ```
I checked your modified `load_checkpoint` codes and my `load_checkpoint` codes, but found no obvious difference. 

- I guess the trouble locates in the `load_checkpoint` section, right? 
- Maybe the extra statement ```{...... if k in model_dict and model_dict[k].shape == pretrained_dict[k].shape}``` affect the results?
- Have you changed any other hyper-parameters like `self.restore_lod0`?

**Comment by youmi-zym** [comment]
Hi @jerryxu9905, the command I train the model is:
`
 python exp_runner_generic.py --mode train --conf ./confs/general_lod1.conf --is_continue --restore_lod0
`
and the general_lod1.conf can be found here: [general_lod1.zip](https://github.com/xxlong0/SparseNeuS/files/9382204/general_lod1.zip).

Others are just minor modifications that don't influence the results.

**Comment by jerryxu9905** [comment]
Hi @youmi-zym,
**Thank you very much for your kind help! Follow your instruction, I succeed training correctly in _lod1_ mode.**

> Hi @jerryxu9905, the command I train the model is: `python exp_runner_generic.py --mode train --conf ./confs/general_lod1.conf --is_continue --restore_lod0` and the general_lod1.conf can be found here: [general_lod1.zip](https://github.com/xxlong0/SparseNeuS/files/9382204/general_lod1.zip).
> 
> Others are just minor modifications that don't influence the results.

The key is that in **_lod1_** mode , We must specify the `--is_continue` and `--restore_lod0` flag in command line. 
So that we can use the trained lod0 network to initialize lod1 network, specifically use the trained `pyramid_feature_network`, `rendering_network_lod0` to initialize `pyramid_feature_network_lod1` , `rendering_network_lod1` respectively.

Again, I would like express my appreciate to you.
